version: "3.11"
services:
  app:
   build: .
   volumes:
    - .:/django
   ports:
    - 8000:8000
   image: application:django
   container_name: music_container
   command: gunicorn music.wsgi:application --bind 0.0.0.0:8000